require 'slack-ruby-bot'
require 'slack-helpbot/bot'
require 'slack-helpbot/about.rb'
require 'slack-helpbot/projects.rb'
require 'slack-helpbot/commands/test.rb'
require 'slack-helpbot/commands/about.rb'
